name: Manual Test Workflow

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: macos-latest
    steps:
      - name: Say Hello
        run: echo "🎉 Hello, GitHub Actions is working!"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Flutter doctor
        run: flutter doctor -v

      

      # Remove KVM enabling step because it's not supported in GitHub Actions.

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64-v8a
          profile: pixel_7_pro
          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -no-window -no-accel
          disable-animations: true
          script: |
            # Wait for the emulator to fully boot up
            sleep 60
            # Run your tests here
            echo "🎉success"
